### ISSUE TITLE
Can't create shapes below size 0.001

### ISSUE THREAD

**Issue by manuel-hegner** [pvandegeer/GeometryShapes#11]
```
2024-06-15T16:08:48     WARNING    Traceback (most recent call last):
              File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeometryShapes\geometry_shapes_tools.py", line 137, in canvasReleaseEvent
              self.stopCapturing()
              File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeometryShapes\geometry_shapes_tools.py", line 125, in stopCapturing
              self.draw_shape()
              File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeometryShapes\geometry_shapes_tools.py", line 190, in draw_shape
              feature.setGeometry(self.geometry(layer))
              File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeometryShapes\geometry_shapes_tools.py", line 207, in geometry
              shape = self.shape()
              File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeometryShapes\geometry_shapes_tools.py", line 319, in shape
              return QgsGeometry.fromRect(self.selection_rect())
             TypeError: QgsGeometry.fromRect(): argument 1 has unexpected type 'NoneType'
```

**Comment by pvandegeer** [comment]
Can you recall how you produced this error? 
Because the dialog should prevent 0 values or values lower than 0,001

**Comment by pvandegeer** [comment]
I' ve increased the number of decimals to 5, otherwise the numbers become unreadable.
I hope this is enough. Maybe I can make them dependant on the zoom level in the future.

If you need smaller number you can easily change the number of decimals in geometry_shapes_dialog_base.ui in the plugin folder.

**Comment by pvandegeer** [comment]
Fixed in commit fc75f4dd812e7befb5fef21d2fc897274231b72e (hopefully)
